### ISSUE TITLE
Rename branch to `main`

### ISSUE THREAD

**Issue by abh** [afiskon/promtail-client#10]
It'd be nice if the main branch was renamed to main instead of the legacy / old term.

Unless a large number of users have active clones and are are sending PRs it's usually enough to just follow the GitHub instructions to rename the branch.

**Comment by afiskon** [comment]
Thanks for letting me know. This project is "on hold" however, as are hundreds other my repositories on GitHub. I have no interest in renaming the main/master branch for all of them.
