### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by imbence** [afiskon/promtail-client#8]
If I try to run the client example I got the following error:
`package github.com/afiskon/promtail-client/promtail
        imports github.com/afiskon/promtail-client/promtail: import cycle not allowed`

**Comment by afiskon** [comment]
@imbence could you please provide exact steps (including Go version, OS version, etc) to reproduce this?

**Comment by imbence** [comment]
I was trying to implement it to my code, and I got the error. But turns out if I test just the example alone, than it runs without the error. So I guess the mistake will be on my side. Thnaks for replying!
